atomist-skills/go-skill

handle.go, internal/types.go, log.go, status.go, transact.go, types.go
Signed-off-by: Christian Dupuis <cd@atomist.com>
=> Try internal package

internal/types.go, log_test.go, transact.go, transact_test.go
Signed-off-by: Christian Dupuis <cd@atomist.com>
=> Support nested entities for transactions

.github/workflows/build-and-test.yaml, log_test.go, transact_test.go
also sets up CI to make sure they stay working
=> repair tests

log.go
- don't continue log request when error is encountered
- add a retry for when network things happen
=> handle skill logging errors

policy/data/gql_async.go, policy/goals/differ.go, policy/goals/entities.go, policy/goals/entities_test.go, policy/goals/types.go, policy/policy_handler/async.go, policy/policy_handler/handler.go, policy/policy_handler/local.go, policy/policy_handler/subscription.go, policy/policy_handler/sync.go
pulling up a couple commits from goal-evaluation-skill that were not included in #32
=> goal-evaluation-skill catch up

handle.go
This will allow us to create a Go skill that can also work as a service. In this way we can add all skill-related endpoints in a subroute of our choosing
=> export createHttpHandler

util/environment.go
Follow the same logic as the [TypeScript code](https://github.com/atomist-skills/skill/blob/21696f154efded41f4cb98eb0e6951ab81839b8c/lib/util.ts#L235-L240).
=> feat: add `IsStaging()` function to detect the running environment

policy/storage/gcs.go
Choose between staging and prod bucket based on the environment the skill is executing in.
=> select correct policy result bucket based on env

policy/policy_handler/handler.go
Add a function to evaluate policy skill locally.
None
=> add a function for evaluating policy skill locally

policy/policy_handler/mocks/base_image_details.go
In order to check public images, re-query without a specified org.
Also return no-data if image is not found instead of failing.
None
=> check public images by querying without context

policy/policy_handler/handler.go
Populate the goal evaluation context.
None
=> populate policy eval context

policy/types/graphql_types.go
Add EPSS to the types now that the platform supports it.
None
=> add epss to types

http_transact.go, log.go, policy/data/gql_async.go, status.go, transact.go
Turns out we were not closing the response body when making an async query - leaky leaky!
None
=> close the response body when making async query

handle.go
This PR closes the body after reading it.
None
=> Close body after reading

policy/policy_handler/subscription.go
Move the log messages so we don't get nil pointers
None
=> fix log message

log_test.go, types.go
<sup>_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._</sup>
Add the entitles type to the list of available URLs
None
=> feat: Add entitlements URL in context

policy/policy.go, spec.go
Add a common struct to consistently define policies.
None
=> add common policy struct

spec.go
Add `defaultValues` field for parameters with multiple values.
None
=> add defaultValues field to spec

spec.go, spec_test.go, test_data/skill.yaml
skill.yaml files are a bit trickier than I remembered.
None
=> handle multi-doc skill yaml correctly

policy/policy.go
Poliwrath will trigger policy evaluation based on events. This allows a policy to specify which events it cares about.
None
=> add a field for policy to specify which events to subscribe to

policy/goals/differ.go, policy/goals/types.go, policy/policy_handler/handler.go, policy/storage/fs.go, policy/storage/gcs.go, policy/storage/storage.go, policy/transact/transact.go, transact.go, transact_test.go, types.go
Make it possible to create Transactions without requiring a skill request context.
None
=> create transactions without skill context

policy/data/gql_async.go
Retry async requests when >= 500 in order to handle transient platform issues
None
=> add retry to async request

environment/environment.go, http_transact.go, policy/storage/gcs.go, transact.go, types.go
- Set remote transaction URL based on environment
- Allow passing of correlation id into transaction request
None
=> add staging url for remote transacting

policy/policy_handler/handler.go, policy/transact/transact.go
Return the transacted entity (if there is one) so that we can use it to create a change event in poliwrath.
None
=> return transacted entity in order to create change event

http_transact.go, policy/transact/transact.go, transact.go, types.go
inject a logger when transacting
None
=> inject a logger when transacting

policy/data/gql_sync.go
add a retry for sync queries
None
=> add a retry for sync queries

policy/data/query/sync.go
also retry sync gql queries
None
=> also retry sync gql queries

policy/data/query/sync.go
basis-t of 0 == no basis-t
None
=> basis-t of 0 == no basis-t

log.go
remove logging to skill endpoint
https://docker.slack.com/archives/C03JU7UR5N0/p1717001696652149
None
=> remove logging to skill endpoint

policy/data/proxy/client.go, policy/data/proxy/types.go, policy/data/source.go, policy/policy_handler/handler.go, policy/policy_handler/proxy.go
add a proxy client for policy results
None
=> add a proxy client for policy results

go.mod, policy/goals/types.go, policy/policy_handler/async.go, policy/policy_handler/subscription.go, policy/storage/sbom.go
This change reads the SBOM from the storage bucket in case it isn't provided in the input data.
None
=> Recreate SBOM

policy/data/proxy/client.go
We missed storing the passed URLs.
None
=> Fix missing assignment of URLs

policy/data/query/jynx/query.go, policy/types/graphql_types.go
This PR adds a missing field to the `Vulnerability` query type.
None
=> Add cisaExploited to Vulnerability query type

policy/data/convert.go, policy/data/query/jynx/types.go
=> wire up cisa-exploited

log.go
allow setting log format to json
None
=> allow setting log format to json

log.go
add labels to local logging
None
=> add labels to local logging

handle.go, log.go, log_test.go
add skill request headers to log context
None
=> add skill request headers to log context

handle.go, log.go, log_test.go
only sanitize the event if it is actually going to be logged
None
=> only sanitize the event if it is actually going to be logged

policy/data/query/client.go
some policies need gqlcontext
None
=> some policies need gqlcontext

policy/data/fixed.go, policy/data/query/fixed.go, policy/data/source.go
fixed data source should be in here for testing so policies can make use of it
None
=> fixed data source should be in here for testing

policy/data/fixed.go, policy/data/source.go
no need for a pointer to an interface
None
=> no need for a pointer to an interface

handle.go, log.go, log_test.go
allow passing custom logger in
None
=> allow passing custom logger in

handle.go, status.go
a couple of tweaks to allow for async skill execution
None
=> a couple of tweaks to allow for async skill execution

handle.go, types.go
allow selecting a handler by func instead of just map
None
=> allow selecting a handler by func instead of just map

policy/policy.go
Now that policy is all in poliwrath, we can simplify things.
None
=> simplify policy

transact.go, types.go
expose transaction creation without request context
None
=> expose transaction creation without request context

status.go
expose skill status without request context
None
=> expose skill status without request context

http_transact.go
=> update transact urls

handle.go
log panic stack trace for diagnostics
None
=> log panic stack trace for diagnostics
