- types.go
This PR exposes the graphql url to the incoming event so it can be used to run GraphQL from the skill.
Needed for:
- https://github.com/atomist-skills/goal-evaluation-skill/pull/53
> Add graphql url to the incoming event

- handle.go
- name.go
- types.go
This PR extends the context of the `EventIncoming` struct with the new `SyncRequest` field. It should allow us to get the sync request's name as the handler's name in the `goal-evaluation-skill`.
This way, the Scout CLI will issue a sync query with name `evaluate_policy_sync_request` and whose metadata contains the purls and whether to transact the results into Datomic.
> Add sync request to types

- log.go
- status.go
- transact.go
Don't log, transact, or send status to the platform when running policies locally.
> Don't log, transact or send status to the platform

- policy/policy_handler/local.go
It is expected that a CommonSubscriptionQueryResult is always available, so we should mock it to a dummy value as goal-evaluation-skill does.
> mock common subscription data for local eval

- go.mod
- go.sum
- policy/policy_handler/legacy/image_packages_by_digest.go
- policy/policy_handler/legacy/image_packages_by_digest_test.go
- policy/policy_handler/local.go
- policy/policy_handler/local_test.go
- types.go
Handles local evaluation queries by mocking them through fixedQueryResults.
Also includes support for the old []Packages style by converting it to a corresponding ImagePackagesByDigest graphql structure.
> add local eval fixedQueryResult test

- policy/data/subscription.go
- policy/policy_handler/local.go
- policy/policy_handler/subscription.go
Felipe has run into an issue with the non-root-user skill, since there is no longer an appropriate method for querying fields off the SyncRequest metadata. This PR adds the SubscriptionDataSource to resolve that blindspot.
SubscriptionDataSource allows querying of objects directly from the subscription results array. It is beneficial to use this data source when it is useful to query by name, possibly allowing earlier data sources to pick up the query first (e.g. local mocking).
I've also updated the local fixed data source to be a prepend action instead of append, to ensure that any local mocks are always handled first. With this, the order of options registered should not impact query behaviour.
> add subscription data source

- policy/goals/entities.go
- policy/goals/entities_test.go
- policy/goals/types.go
cherry-pick from atomist-skills/goal-evaluation-skill@41def6575719cf4d1ece603f636a83f0755e992a
> retract attributes when no-data

- policy/goals/types.go
- policy/policy_handler/handler.go
cherry pick from atomist-skills/goal-evaluation-skill@d1dda2efa4743a3d06ed67eab4a6412d517a3e5e
> async query is not no data

- policy/goals/entities.go
- policy/goals/entities_test.go
- policy/policy_handler/handler.go
cherry-pick of atomist-skills/goal-evaluation-skill#221
> If we do not yet have results for a specific policy, attempting to retract fields within its result entity fails.
> fix: do not retract from non-existent entities

- policy/data/subscription.go
There was an index mismatch here which would cause unnecessary failures when using a non-zero index.
I have an in-progress change still about switching this to use named keys, but until then this index mismatch blocks atomist-skills/policy-base-images#45
> fix subscription data source ix

- policy/policy_handler/async.go
- policy/policy_handler/handler.go
Allow policies to explicitly register WithAsync early to ensure its priority is higher than other data sources (namely the SyncGraphqlDataSource).
This will need to be consumed in policy-base-images to prevent sync queries that are currently happening.
> export policy_handler.WithAsync

- policy/policy_handler/mocks/base_image.go
- policy/policy_handler/mocks/base_image_test.go
We should not add this library/ prefix to DOI base images in the GetBaseImagesMock. Datomic does not have this prefix, which was causing mismatches in approved-base-image's supportedTags query on sync request evaluations.
> remove library/ from base image mock

- .github/CODEOWNERS
- .github/pull_request_template.md
- policy/policy_handler/handler.go
Add function for getting httpHandler from a policy skill so it can be hosted elsewhere.
> make it possible to get the httphandler from a policy skill

- middleware/signing.go
- middleware/signing_test.go
<sup>_Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change._</sup>
Validate the `X-Skill-Signature-256` header to trust incoming requests.
None
> feat: middleware to validate signed skill requests

- policy/policy_handler/mocks/base_image_details.go
- policy/policy_handler/mocks/base_image_details.test.go
- policy/policy_handler/mocks/builder.go
Need to mock image-details-by-digest for the no-stale-base-images policy.
This is just a temporary fix, a proper refactoring will come after.
None
> mock image-details-by-digest for no-stale-base-images

- policy/policy_handler/mocks/base_image_details.go
- policy/policy_handler/mocks/base_image_details.test.go
Use imageDetailsByDigest to fetch the base image details because it handles indexes.
None
> fetch base image details using imageDetailsByDigest

- policy/data/gql_sync.go
- policy/types/graphql_types.go
This PR replaces `json.Unmarshal` with `graphql.UnmarshalGraphQL` and reverts the JSON struct tags from camelCase to snake_case (e.g. `publishedAt` -> `published_at`).
None
> Replace json.Unmarshal with graphql.UnmarshalGraphQL

- policy/goals/types.go
- policy/policy_handler/subscription.go
- policy/types/types.go
We now have a shiny new provenance mode flag that we should use instead of messing around with source maps.
https://github.com/docker/scout-cli-plugin/pull/469
> use provenance mode flag instead of source map

- policy/policy_handler/subscription.go
While we should always populate `Provenance`, `ProvenanceBaseImage` relies on having a base image.
None
> only populate base image provenance when it is provided

- policy/data/gql_sync.go
- policy/data/source.go
`poliwrath` would like to pass a correlation id into GQL queries, and also be able to operate purely against public data, with no organizational context.
None
> allow for passing a correlation id and having no organization

- policy/goals/types.go
- policy/policy_handler/subscription.go
populate the platform variant on the sbom when it is in the subscription result
None
> populate platform variant on sbom

- policy/data/gql_sync.go
Pretending that JSON is EDN is never going to end well.
None
> helps if we send edn when we say we are sending edn

- policy/data/gql_sync.go
- policy/policy_handler/sync.go
Set it up beautifully but never actually set `basis-t` from the evaluation context.
None
> actually set basis-t from the eval context

- policy/data/gql_async.go
- policy/data/gql_sync.go
It is nice that the sync GQL data source supports both the skill gql endpoint and the public one. But that only works if it is sending JSON, so lets do that.
None
> sync gql queries should be json because that's what the public api supports

- http_transact.go
- policy/transact/transact.go
Warning and swallowing the error isn't great. return the error so the caller can decide what to do with it.
None
> errors should probably be returned as errors

- policy/data/query/sync.go
log gql response at debug because they can be big
None
> log gql response at debug because they can be big

- policy/goals/differ.go
AFAIK the only slices we use in policy results do not care about the ordering. Just the overall list of results and the locations of packages. This will make the hash stable when the ordering ends up changing.
None
> treat slices as sets when hashing

- http_transact.go
- status.go
- test/simulate.go
- transact.go
Instead of creating new httpClients everywhere, let's share the DefaultClient.
Also add a retry for when sending skill execution status fails.
None
> use shared httpClient and retry status sending failures

- policy/data/proxy/client.go
- policy/policy_handler/handler.go
- policy/policy_handler/proxy.go
This PR extracts the proxy url and makes it a parameter.
None
> Extract proxy url

- policy/data/vulnerabilities.go
- sbom/normalization/normalization.go
If `Vulnerabilities` is provided in the SBOM then we can assume VEX has been applied. And if we are fetching the vulnerabilities alongside the packages from the platform then VEX has been applied. But if we have the packages and are fetching public vulnerabilities, then we need to apply VEX here.
None
> apply vex statements when using public vuln data

- policy/skills/parse.go
- policy/skills/parse_test.go
parse int32 args correctly so that consumers don't have to worry about what arg type they pass in
None
> [SDC-1169] parse int32 args correctly

- policy/data/vulnerabilities.go
- policy/data/vulnerabilities_test.go
This PR refactors the VEX matching logic as I've identified the following bugs:
- The product id was not being taken into account when matching the purl.
- All CVEs under the same purl were being considered affected when there was a match as the CVE ID was not being taken into account.
Furthermore, I've extended the logic to allow VEX matching when no subcomponents.
See the unit tests for more details.
None
> [SDC-1140] - fix(vex): allow VEX matching when no subcomponents

- policy/data/proxy/client.go
- policy/data/source.go
- policy/policy.go
I had hoped to remove this from go-skill and handle it purely in poliwrath, but it is in fact just simpler to maintain this interface for now and make this change later.
None
> add proxy-client back in

- policy/types/types.go
This is breaking some downstream policy processing because the JSON has upper case keys.
None
> Fix missing JSON struct tags
